import { Inter } from "next/font/google";
import "../globals.css";
import Navbar from "../components/Navbar/Navbar";
import { ThemeProvider } from "../utils/MaterialTailwind";
import StoreProvider from "../store/StoreProvider";
import AuthWrapper from "../components/Auth/AuthWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThemeProvider>
        <body className={inter.className}>
          <StoreProvider>
            <div className="flex flex-col h-screen">
              <Navbar />

              <main className="flex-grow">
                <AuthWrapper>{children}</AuthWrapper>
              </main>
            </div>
          </StoreProvider>
        </body>
      </ThemeProvider>
    </html>
  );
}
